### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by goranapo** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#3]
Everything works perfect, i must admit, GREAT job.
One small thing is that i must click twice on "Empty Cart" to be actually empty.
There is no issue with css, but i have issue with css :), i have no clue how to obtain what i need.
I just want shop to look better, like attached file for example (i made it in photoshop), can anyone help me?
![btc-shop-example](https://cloud.githubusercontent.com/assets/7156503/14089838/5a9f98b8-f537-11e5-9e53-9d5574449fa7.jpg)

**Comment by coinables** [comment]
If you or anyone else wants to provide a new CSS style, I'm totally open for it. Just create a pull request with the new CSS style and a name for the style (example: style_blue.css) in order to keep the original style still available.  
But the layout is a different issue. One of the things I didn't take into account, was users wanting a different layout, so much of the layout is hard-coded. It could be changed, but it would take a bit of a re-write. If anyone is up for rewriting index.php so the layout could be 100% dynamic based on the CSS that would be awesome.
