### ISSUE TITLE
Changing the currency

### ISSUE THREAD

**Issue by acrobaat** [coinables/Blockchain-Receive-Payments-API-Shopping-Cart#5]
Hi,
How do I change this code to accept Euro's (or any other currency)
I found the $ signs and changed them into €, but how is the calculation made into bitcoins?

**Comment by coinables** [comment]
Calculation is done on the [index.php page](https://github.com/coinables/Blockchain-Receive-Payments-API-Shopping-Cart/blob/master/index.php#L11-L17) and then stored in a session while the user browses so that prices don't change while they shop. https://github.com/coinables/Blockchain-Receive-Payments-API-Shopping-Cart/blob/master/index.php#L11-L17

Current source is from Coinbase, but you can change it to whatever you want. For example in Euros you can get it from btc-e or kraken. 

Example using btc-e BTC/EUR conversion. 
Change lines 11-17
```
//get current exchange rate
if(!isset($_SESSION['exr'])){
$url = "https://btc-e.com/api/3/ticker/btc_eur";
$json = json_decode(file_get_contents($url), true);
$price = $json["btc_eur"]["last"];
$_SESSION['exr'] = $price;
}
```
